docs: more info when a bad commit format is used

diff --git a/.husky/commit-msg b/.husky/commit-msg
--- a/.husky/commit-msg
+++ b/.husky/commit-msg
@@ -1,7 +1,7 @@
 #!/bin/sh
 # This script checks if the commit message follows a consistent format(usually useful for consistency and devops)
 if ! head -1 "$1" | grep -qE "^(feat|fix|ci|chore|docs|test|style|refactor|perf|build|revert)(\(.+?\))?: .{1,}$"; then
-    echo "Aborting commit. Your commit message is invalid." >&2
+    echo "Aborting commit. Your commit message is invalid. See accepted format here: https://commitizen.github.io/cz-cli/" >&2
     exit 1
 fi
 if ! head -1 "$1" | grep -qE "^.{1,88}$"; then
